### ISSUE TITLE
Checklist of meza tags current working in Rocky/RHEL8

### ISSUE THREAD

**Issue by djflux** [djflux/meza#6]
Below are a list of meza tags that have completed a `meza deploy monolith` with no errors using the `rhel8-35.x` branch in this repository. This checklist will be updated once that tag is working successfully. 

### Tested on RHEL 8.x

- [x] always
- [x] apache-php
- [x] autodeployer
- [x] backup-cleanup
- [x] backup-servers
- [x] base
- [x] controller
- [x] cron
- [x] database
- [x] elasticsearch
- [x] latest
- [x] mediawiki
- [x] mediawiki-composer-extensions
- [x] mediawiki-core-skins
- [x] mediawiki-file-perms
- [x] mediawiki-git-core-extensions
- [x] mediawiki-git-extensions
- [x] mediawiki-git-local-extensions
- [x] mediawiki-git-submodules
- [x] mediawiki-httpd-reload
- [x] mediawiki-latest
- [x] mediawiki-local-skins
- [x] mediawiki-mediawiki
- [x] mediawiki-mediawiki-core
- [x] mediawiki-search-index
- [x] mediawiki-skins
- [x] mediawiki-smw-data
- [x] mediawiki-update.php
- [x] mediawiki-verify-wiki
- [x] memcached
- [x] parsoid

### Tested on Rocky 8.6

- [x] always
- [x] apache-php
- [x] autodeployer
- [x] backup-cleanup
- [x] backup-servers
- [x] base
- [x] controller
- [x] cron
- [x] database
- [x] elasticsearch
- [x] latest
- [x] load-balancer
- [x] mediawiki
- [x] mediawiki-composer-extensions
- [x] mediawiki-core-skins
- [x] mediawiki-file-perms
- [x] mediawiki-git-core-extensions
- [x] mediawiki-git-extensions
- [x] mediawiki-git-local-extensions
- [x] mediawiki-git-submodules
- [x] mediawiki-httpd-reload
- [x] mediawiki-latest
- [x] mediawiki-local-skins
- [x] mediawiki-mediawiki
- [x] mediawiki-mediawiki-core
- [x] mediawiki-search-index
- [x] mediawiki-skins
- [x] mediawiki-smw-data
- [x] mediawiki-update.php
- [x] mediawiki-verify-wiki
- [x] memcached
- [x] parsoid

**Comment by djflux** [comment]
Had to update the "latest" tag because this morning Rocky published ansible-5.4 and python38 which broke meza in the middle of a deploy. 

`rhel8-35.x` branch as of 9b44a25 updates everything EXCEPT python and ansible.

**Comment by djflux** [comment]
`rhel8-35.x` as of commit [336c3c9](https://github.com/djflux/meza/commit/336c3c985631e229cd9d51ccdde54535c953c0eb) runs all the way to completion.

Here are the instructions to replicate.

* install Rocky 8.6 (can use kickstart file below to automate)
* Login as standard user
* Run the following commands

```
sudo git clone https://github.com/djflux/meza.git /opt/meza
cd /opt/meza
sudo git checkout rhel8-35.x
sudo bash /opt/meza/src/scripts/getmeza.sh
sudo meza deploy monolith
```

Provide hostname and database password (if desired) then wait about 15-45 minutes.

Need to test on a RHEL8 installation.

### Kickstart file

```
lang en_US
keyboard us
timezone America/Chicago --isUtc
rootpw INSERT_YOUR_CRYPTED_PASSWORD_HERE --iscrypted
#platform x86_64
reboot
text
url --url=https://ord.mirror.rackspace.com/rocky/8/BaseOS/x86_64/os
bootloader --append="rhgb quiet crashkernel=auto"
zerombr
clearpart --all --initlabel
autopart
auth --passalgo=sha512 --useshadow
selinux --enforcing
firewall --enabled --http --ssh
skipx
firstboot --disable
%packages
@^minimal-environment
@network-tools
git
vim-enhanced
net-tools
%end

%post --nochroot --log=/mnt/sysimage/var/log/ks-post.log
cat >> /mnt/sysimage/etc/profile.d/fluxstuff.sh << EOF
alias dir='ls --color -la | more'
alias vi=vim

export PS1="[\u@\h \w]\\\\$ "
EOF
%end
```

**Comment by djflux** [comment]
Kickstart files added into `rhel8-35.x branch` as of commit 84647b0

**Comment by djflux** [comment]
> Had to update the "latest" tag because this morning Rocky published ansible-5.4 and python38 which broke meza in the middle of a deploy.
> 
> `rhel8-35.x` branch as of [9b44a25](https://github.com/djflux/meza/commit/9b44a25d8c13ecbd612d358a20e4f035e38fbbc0) updates everything EXCEPT python and ansible.

As of commit As of commit 03218f2 exclusions for python38 and ansible have been placed into the dnf/yum repo files in `/etc/yum.repos.d` by `getmeza.sh` on both Rocky and RHEL8. This change will allow ansible and python36 to be updated properly and also not update ansible to a version greater than 2.9.x.
